"""Add workspace models

Revision ID: 1fb4e721dfcc
Revises: 27e1f4b28402
Create Date: 2026-05-05 21:40:39.078780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb4e721dfcc'
down_revision: Union[str, None] = '27e1f4b28402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'QA_LEAD', 'QA_ENGINEER', 'VIEWER', name='workspacerole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspace_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_type', sa.Enum('BUG', 'TEST', 'PRESET', 'STYLE', name='workspacetemplatetype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_templates_id'), 'workspace_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_templates_workspace_id'), 'workspace_templates', ['workspace_id'], unique=False)
    with op.batch_alter_table('jira_connections') as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_jira_connections_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_jira_conn_workspace_id', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jira_field_mappings') as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jira_field_mappings_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_jira_fields_workspace_id', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jobs') as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_jobs_workspace_id', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('default_workspace_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_default_workspace_id', 'workspaces', ['default_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_default_workspace_id', type_='foreignkey')
        batch_op.drop_column('default_workspace_id')

    with op.batch_alter_table('jobs') as batch_op:
        batch_op.drop_constraint('fk_jobs_workspace_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('jira_field_mappings') as batch_op:
        batch_op.drop_constraint('fk_jira_fields_workspace_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jira_field_mappings_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('jira_connections') as batch_op:
        batch_op.drop_constraint('fk_jira_conn_workspace_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jira_connections_workspace_id'))
        batch_op.drop_column('is_shared')
        batch_op.drop_column('workspace_id')
    op.drop_index(op.f('ix_workspace_templates_workspace_id'), table_name='workspace_templates')
    op.drop_index(op.f('ix_workspace_templates_id'), table_name='workspace_templates')
    op.drop_table('workspace_templates')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
