"""Add workspace_id to audit_logs

Revision ID: 6ec5c316e8e2
Revises: 1fb4e721dfcc
Create Date: 2026-05-05 21:45:42.171982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec5c316e8e2'
down_revision: Union[str, None] = '1fb4e721dfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_logs_workspace_id', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_workspace_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('jira_field_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jira_field_mappings_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('jira_connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_column('workspace_id')

    # ### end Alembic commands ###
