"""add xray cloud credentials to jira connections

Revision ID: 980890c8758c
Revises: a1c2d3e4f5a6
Create Date: 2026-05-05 21:03:00.476426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980890c8758c'
down_revision: Union[str, None] = 'a1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_connections', sa.Column('xray_cloud_client_id', sa.String(), nullable=True))
    op.add_column('jira_connections', sa.Column('encrypted_xray_cloud_client_secret', sa.String(), nullable=True))
    op.drop_index('ix_refresh_sessions_token_jti', table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_token_jti'), 'refresh_sessions', ['token_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_token_jti'), table_name='refresh_sessions')
    op.create_index('ix_refresh_sessions_token_jti', 'refresh_sessions', ['token_jti'], unique=False)
    op.drop_column('jira_connections', 'encrypted_xray_cloud_client_secret')
    op.drop_column('jira_connections', 'xray_cloud_client_id')
    # ### end Alembic commands ###
